version: "3.9"

services:

  grafana:
    image: grafana/grafana:8.0.6-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana

  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
      - ./rules.yml:/etc/prometheus/rules.yml

  alertmanager:
    image: prom/alertmanager:v0.22.2
    ports:
      - "9093:9093"
    volumes:
      - alert-data:/alertmanager
      - alert-configs:/etc/alertmanager

  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.3
    environment:
      TELEGRAM_ADMIN: "<user_id>"
      TELEGRAM_TOKEN: "<bot_id>"
      ALERTMANAGER_URL: http://alertmanager:9093
      STORE: bolt
      BOLT_PATH: /data/bot.db
    volumes:
      - alert-bot-data:/data

  node-exporter:
    image: prom/node-exporter:v1.2.0
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
  alert-data:
  alert-configs:
  alert-bot-data: